### ISSUE TITLE
While installing the package got " UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 12"

### ISSUE THREAD

**Issue by justinscodespace** [bandprotocol/pylibra#5]
Hi,
First of all I'm new to python, When I try to install pylibra I got the following error message..

ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JUSTIN~1.JOH\AppData\Local\Temp\pip-install-hgnspb3u\pylibra\setup.py", line 5, in <module>
        README = open(os.path.join(os.path.dirname(__file__), "README.md")).read()
      File "c:\users\justin.johns\appdata\local\programs\python\python37-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 12: character maps to <undefined>
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\JUSTIN~1.JOH\AppData\Local\Temp\pip-install-hgnspb3u\pylibra\

Python version 3.7.3
pip version 19.1.1
Can anybody tell me how to fix this, It would be great :-)

**Comment by sorawit** [comment]
#6 should fix this. I'll close this for now, but please let me know if the problem still persists.
